
//     DATA ACTIONTYPES      //////////////////////////////////////
export const SAVE_USER_COLLECTIONS_DATA_SUCCESS = 'SAVE_USER_COLLECTIONS_DATA_SUCCESS';
export const SAVE_COLLECTIONS_NAMES_SUCCESS = 'SAVE_COLLECTIONS_NAMES_SUCCESS';
export const SAVE_ACCOUNT_NAMES_SUCCESS = 'SAVE_ACCOUNT_NAMES_SUCCESS';
export const SAVE_CURRENT_COLLECTION_SUCCESS = 'SAVE_CURRENT_COLLECTION_SUCCESS';