
//     NAVIGATION ACTIONTYPES      //////////////////////////////////////
export const DISPLAY_DRAWER_OVERLAY_SUCCESS = 'DISPLAY_DRAWER_OVERLAY_SUCCESS';
export const TOGGLE_DRAWER_OVERLAY_SUCCESS = 'DISPLAY_DRAWER_OVERLAY_SUCCESS';