
//     NAVIGATION ACTIONTYPES      //////////////////////////////////////
export const DISPLAY_DRAWER_OVERLAY_SUCCESS = 	'DISPLAY_DRAWER_OVERLAY_SUCCESS';
export const TOGGLE_DRAWER_OVERLAY_SUCCESS = 	'TOGGLE_DRAWER_OVERLAY_SUCCESS';
export const NAV_BAR_TITLE_CHANGE_SUCCESS = 	'NAV_BAR_TITLE_CHANGE_SUCCESS';